{
 "title": "Lviv Temperature",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Temperature d65e",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Temperature\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d65e'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Temp b5b2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Temperature\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d000411b5b2'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Temp b5da",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Temperature\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d000411b5da'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Temp d5b8",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Temperature\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d5b8'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Pressure d65e",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Pressure\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d65e'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Humidity d65e",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Humidity\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d65e'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Humidity b5b2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Humidity\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d000411b5b2'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Humidity b5da",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Humidity\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d000411b5da'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Humidity d5b8",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Humidity\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d5b8'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "ef30 Battery",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "ef30 Link",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "ef30 Voltage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 8 },
   "format": "mvolt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Temperature\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  $__timeFilter(TS)\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Humidity\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  $__timeFilter(TS)\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Pressure\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  $__timeFilter(TS)\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Battery Life",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Battery\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d5b8'\nORDER BY TS"
    },
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  Battery\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d65e'\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Link Quality",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  LinkQuality\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d65e'\nORDER BY TS"
    },
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  LinkQuality\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d000411b5b2'\nORDER BY TS"
    },
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  LinkQuality\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d0003f0d5b8'\nORDER BY TS"
    },
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  Device AS metric,\n  LinkQuality\nFROM Xiaomi_Temperature_Sensors_Lviv\nWHERE\n  Device = 'zigbee2mqtt/0x00158d000411b5da'\nORDER BY TS"
    }
   ]
  }
 ]
}